name: Docker CI & CD

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: cd todo-app && docker-compose build

      - name: Run Docker Compose
        run: cd todo-app && docker-compose up -d & sleep 5

      - name: Wait for services to be ready
        run: cd todo-app && docker-compose run app bash -c 'while !</dev/tcp/localhost/3000; do sleep 1; done'

      - name: Run unit tests
        run: cd todo-app && docker-compose run app npm test

      - name: Run integration tests
        run: cd todo-app && docker-compose run app npm install cypress cypress-json-results && docker-compose run app npx cypress run

      - name: Notify on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"✨ Great News! The CI & CD workflow completed successfully! All tests passed smoothly. :tada:"}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ Uh-oh! The CI & CD workflow encountered issues and failed. Immediate attention is needed. :warning:"}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Stop and remove Docker containers
        run: cd todo-app && docker-compose down
